### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by guilhermedelyra** [wmalarski/astro-albums#1]
idk if this repo is still being maintained, but login isnt working anymore :)

![image](https://github.com/wmalarski/astro-albums/assets/23236957/25777025-0bb3-4f2d-bed1-b1fef928c602)
![image](https://github.com/wmalarski/astro-albums/assets/23236957/4ba15d93-7c3a-4983-9779-05b9e73b1ae0)

**Comment by wmalarski** [comment]
hello. I just updated this repo to the latest Astro version to test the new view transition API. I also updated all supabase related auth flows to new patterns. Magic link login is now working but this error is caused by my supabase instance going into hibernation mode. It's going to happen again after probably a week. I'm okay with this app crashing.
